### ISSUE TITLE
Failed to access .local-chromium

### ISSUE THREAD

**Issue by LucasNmn** [plotly/Plotly.NET#295] opened 2022-06-08 11:39 UTC
Hi, 

I'm trying to export an svg string in an ASP.NET WebApp with Plotly.Net vers 2.0 . It works fine on my local computer but when i try rolling it out on an IIS server i get "no permission on _c:/path-to-file/.local-chromium_" ). The issue might be a wrong installation of the chromium browser but I'm not quite sure. Maybe I have to set the executablepath for PuppeteerSharp but I don't know where to do this.

Do you have any idea how to fix this?

**Comment by kMutagene** [comment] 2022-06-10 07:46
Since https://github.com/plotly/Plotly.NET/pull/264 got merged, i think you should be able to set the executable path via `PuppeteerSharpRendererOptions.localBrowserExecutablePath` :

https://github.com/plotly/Plotly.NET/blob/b8f1d888fdf2e52125ba9ed32107c59fdbd377f5/src/Plotly.NET.ImageExport/PuppeteerSharpRenderer.fs#L12-L18

Just set it to a path via mutable assignment (`PuppeteerSharpRendererOptions.localBrowserExecutablePath <- Some "path/here"`)

**Comment by kMutagene** [comment] 2022-06-10 09:40
On another note, it might be that your application simply does not have the permissions to access the content of .local-chromium. It has been some time since i used IIS, but there is a user (`IIS_USRS` or `IUSR` or something like that), which symbolizes the access rights of your IIS application. If your .local-chromium folder is persistent, adding full access for those users might do the trick.

**Comment by LucasNmn** [comment] 2022-06-10 13:23
Thanks for your advice. I've updated from Version 2.0 prev 6 to Version 2.0. I'm now getting some strange behaviour. When I'm exporting an image to an svg string with `chart.ToSVGString()` the functions hangs up in an endless loop. When I'm generating an image with :

`chart = GenericChart
           .ofTraceObject(true, trace)
           .WithLayout(layout)
           .WithConfig(config)
           .WithShapes(shapeList)
           .Show();`,

It's exporting an image. I added the executable like:

`Plotly.NET.ImageExport.PuppeteerSharpRendererOptions.localBrowserExecutablePath = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";`

But with and without the behaviour isn't changing at all.

**Comment by kMutagene** [comment] 2022-06-11 13:29
is this done from C#? If so, i guess the `FSharpOption` is wrapped incorrectly when you are assigning just a string.

**Comment by LucasNmn** [comment] 2022-06-13 06:04
> is this done from C#? If so, i guess the `FSharpOption` is wrapped incorrectly when you are assigning just a string.

Yes, from C#

**Comment by LucasNmn** [comment] 2022-06-20 06:04
Hello. Do you have a solution yet.

**Comment by kMutagene** [comment] 2022-06-20 08:09
No i do not have a solution, i have no way of debugging your very specific issue in your very specific use case without any reproducible code.

But i have identified a possible problem in my last answer:

> If so, i guess the FSharpOption is wrapped incorrectly when you are assigning just a string.

So i'd suggest trying to set an actual `FSharpOption<string>` like i suggested:

```csharp
using Plotly.NET.CSharp;
using Plotly.NET.ImageExport;
using Microsoft.FSharp.Core;

var path = @"executable/path/to/chrome.exe";

FSharpOption<string> opt = FSharpOption<string>.Some(path);

Plotly.NET.ImageExport.PuppeteerSharpRendererOptions.localBrowserExecutablePath = opt;

Chart.Line<int,int,string>(
    x: new int[]{1,2,3,4},
    y: new int[]{1,2,3,4}
).SaveJPG(@"somewhere\test.jpg")
```

this works in a notebook without issues, so any problems here are specific to your use case in IIS, and might be related to your application not having the rights to use the chromium instance

**Comment by kMutagene** [comment] 2022-06-27 11:34
Closing this until we get either feedback or reproducible code

**Closed as completed by kMutagene** 2022-06-27 11:34 UTC
