### ISSUE TITLE
Strong named assembly ask

### ISSUE THREAD

**Issue by LittleLittleCloud** [plotly/Plotly.NET#239] opened 2021-11-12 23:00 UTC
Hi Plotly

I'm looking into using Plotly.net in model builder extension to present some nice chart, but in VS world, everything needs to be strong-named, which blocks me from using this amazing library.

I search through the issue list and found a similar ask this september #175. Just wondering if that's still on the plate and if there's an estimation on that to be completed.

Regards

**Comment by LittleLittleCloud** [comment] 2021-11-12 23:19
#240

**Comment by WhiteBlackGoose** [comment] 2021-11-13 06:00
That issue is there exactly to be not forgotten. There's no need to duplicate.

**Comment by kMutagene** [comment] 2022-05-30 19:44
Closing as duplicate of #175

**Closed as completed** 2022-05-30 19:44 UTC
