### ISSUE TITLE
Newtonsoft.Json reference

### ISSUE THREAD

**Issue by wilsoncg** [plotly/Plotly.NET#4] opened 2017-10-17 11:12 UTC
### Description

nuget package references Newtonsoft.Json v=10.0.0, packages .config references Newtonsoft.Json v=9.0.1

### Repro steps

Please provide the steps required to reproduce the problem

1. Reference FSharp.Plotly package v1.0.3

2. Receive error message
```
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at FSharp.Plotly.GenericChart.toChartHTML(GenericChart gChart)
   at FSharp.Plotly.GenericChart.toEmbeddedHTML(GenericChart gChart)
```

### Expected behavior

Nuget package page lists Newtonsoft.Json version referenced

### Actual behavior

Nuget package page does not display referenced package, listed as:
Newtonsoft.Json (>= 0.0.0)

### Thoughts?

I'm not familiar enough with packet, but I'd be happy to try and fix up this discrepancy if you can point me in the right direction.

Alternatively, fsharp.plotly could be changed to use the JavaScriptSerializer in System.Web.Script.Serialization instead of Newtonsoft.Json. Or will that cause further issues when targeting Mono, etc?

**Comment by realvictorprm** [comment] 2017-10-20 19:47
I run into no problems. Just installed it via nuget and my project still builds (without changes to the source code).

**Comment by realvictorprm** [comment] 2017-10-20 19:54
Okay sorry, this issue is still valid @muehlhaus.
```
Ein Ausnahmefehler des Typs "System.IO.FileLoadException" ist in FSharp.Plotly.dll aufgetreten.
Die Datei oder Assembly "Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
```

So version of Newtonsoft.Json is still wrong.

**Comment by kMutagene** [comment] 2020-09-16 08:39
This did not show up since 3 years so I'll close this. feel free to report new issues if the problem is still present

**Closed by kMutagene** 2020-09-16 08:39 UTC
