### ISSUE TITLE
Chart.Column missing parameters and abstractions

### ISSUE THREAD

**Issue by gaviei** [plotly/Plotly.NET#137] opened 2021-08-23 18:41 UTC
The example "Bar Chart with Direct Labels" in https://plotly.com/python/bar-charts/ requires the assignment of the property "textposition" which is missing in the abstraction:

![](https://user-images.githubusercontent.com/7762947/130376428-dbb9696f-2db6-46bc-beb4-375a044af155.png)

**Comment by kMutagene** [comment] 2021-08-26 11:07
Seems like the problem is `StyleParam.TextPosition` not having an `Auto` field

**Comment by kMutagene** [comment] 2021-08-27 07:06
I renamed the issue, please add missing properties and abstraction to this issue directly

**Comment by MaheshPunna** [comment] 2021-09-14 16:37
```
let products = ["Product A"; "Product B"; "Product C"];
let sfValues = [20; 14; 23]
Chart.Column (    products,
    sfValues,
    Labels= sfValues,
    TextPosition = StyleParam.TextPosition.TopCenter
)
```
Current Behavior:
![image](https://user-images.githubusercontent.com/7539514/133298067-239acc10-4327-47b6-9e96-081924ca663b.png)

Expected:

![image](https://user-images.githubusercontent.com/7539514/133298128-7c850fcd-4ccb-4678-89b1-039e5fbcad97.png)

@kMutagene  TextPosition for Chart.Column is not working

**Comment by kMutagene** [comment] 2021-09-14 19:23
@MaheshPunna Bart traces only support these text position parameters: "inside" | "outside" | "auto" | "none" (https://plotly.com/javascript/reference/bar/#bar-textposition)

If you use auto as used in the plotly js examples [here](https://plotly.com/javascript/bar-charts/#bar-chart-with-direct-labels), it works as intended:

```fsharp
let products = ["Product A"; "Product B"; "Product C"];
let sfValues = [20; 14; 23]
Chart.Column (    products,
    sfValues,
    Labels= sfValues,
    TextPosition = StyleParam.TextPosition.Auto
)
|> Chart.show
```

![image](https://user-images.githubusercontent.com/21338071/133320592-f84fb222-a7dc-4ec0-bd90-f270a7304252.png)

Note that we only recently merged `TextInfoPosition` and `TextPosition`, so this will be available in the next release.

**Comment by kMutagene** [comment] 2021-09-14 19:54
Closing this, all parameters will be available on the next release.

**Closed as completed by kMutagene** 2021-09-14 19:54 UTC
Labels: Area: MissingAbstraction
