### ISSUE TITLE
Layout.init missing textinfo initializer

### ISSUE THREAD

**Issue by gaviei** [plotly/Plotly.NET#158] opened 2021-08-26 23:15 UTC
```
#r "nuget: Plotly.NET, 2.0.0-preview.6"
#r "nuget: Plotly.NET.Interactive, 2.0.0-preview.6"
open Plotly.NET

let colors = ["gold"; "mediumturquoise"; "darkorange"; "lightgreen"]
let labels = ["Oxygen"; "Hydrogen"; "Carbon_Dioxide"; "Nitrogen"]
let values = [4500; 2500; 1053; 500]

let layout = 
    let obj = Layout.init(Font = Font.init(Size = 12.0))
    obj?hoverinfo <- "label+percent"
    obj?textinfo <- "value"
    obj

Chart.Pie(Labels=labels, values=values, Colors = colors)
|> Chart.withLayout(layout)
```

**Comment by kMutagene** [comment] 2021-08-27 07:02
duplicate of #157, this must be set on the trace, not the layout. https://plotly.com/javascript/reference/pie/#pie-textinfo

**Closed as completed by kMutagene** 2021-08-27 07:02 UTC
