### ISSUE TITLE
Layout.init missing insideTextOrientation initializer

### ISSUE THREAD

**Issue by gaviei** [plotly/Plotly.NET#159] opened 2021-08-26 23:15 UTC
Related example: https://plotly.com/python/pie-charts/#controlling-text-orientation-inside-pie-sectors
```
#r "nuget: Plotly.NET, 2.0.0-preview.6"
#r "nuget: Plotly.NET.Interactive, 2.0.0-preview.6"
open Plotly.NET

let colors = ["gold"; "mediumturquoise"; "darkorange"; "lightgreen"]
let labels = ["Oxygen"; "Hydrogen"; "Carbon_Dioxide"; "Nitrogen"]
let values = [4500; 2500; 1053; 500]

let layout = 
    let obj = Layout.init()
    obj?insidetextorientation <- "radial"
    obj

Chart.Pie(Labels=labels, values=values, Textinfo="label+percent")
|> Chart.withLayout(layout)
```

**Comment by kMutagene** [comment] 2021-08-27 07:01
duplicate of #157 , this must be set on the pie trace, not the layout: https://plotly.com/javascript/reference/pie/#pie-insidetextorientation

**Closed as completed by kMutagene** 2021-08-27 07:01 UTC
